
#ROBOT A MQTT BRIDGE CONFIG

mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: roboA
    port: 1883
    keepalive: 60
serializer: msgpack:dumps
deserializer: msgpack:loads
bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge   
    msg_type: tf2_msgs.msg:TFMessage              #change this to our custom message type
    topic_from: /comm/roboB
    topic_to: roboB
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: tf2_msgs.msg:TFMessage              #change to custom message type
    topic_from: roboA
    topic_to: /comm/roboA